@startuml ListaPrestiti

class Lista_Prestiti {
    - prestiti: List<Prestito>

    + getPrestiti(): List<Prestito>
    + aggiungiPrestito(p: Prestito): void
    + rimuoviPrestito(p: Prestito): void
    + aggiornaRitardi(): void
    + setPrestiti(prestiti: List<Prestito>): void
    + OrdinaLibriPerScadenza(cmp: Comparator<Prestito>): void
    + salvataggioPrestiti(nomefile: String): void
    + letturaPrestiti(nomefile: String): Lista_Prestiti
}

@enduml
