@startuml ControllerSchermataRitardo

class ControllerSchermataRitardo {
    - btnLista: Button
    - btnAggiungi: Button
    - btnIndietro: Button

    + init(): void
    + schermataVisualizzaRitardo(): void
    + tornaIndietro(): void
}
@enduml