@startuml ControllerSchermataVisualizzaRitardo

class ControllerSchermataVisualizzaRitardo {
    - tabellaRitardo: TableView<Prestito>
    - colonnaISBN: TableColumn<Prestito,String>
    - colonnaUtente: TableColumn<Prestito,Utente>
    - colonnaID: TableColumn<Prestito,Integer>
    - colonnaScadenza: TableColumn<Prestito,LocalDate>
    - colonnaElimina: TableColumn<Prestito,Void>
    - colonnaModifica: TableColumn<Prestito,Void>
    - btnIndietro: Button
    - btnRicerca: Button

    + init(): void
    + aggiungiBtnModifica(): void
    + aggiungiBtnElimina(): void
    + cerca(): void
    + tornaIndietro(): void
}

@enduml