@startuml ControllerSchermataAggiungiLbro

class ControllerSchermataAggiungiLibro {
    - titolo: TextField
    - ISBN: TextField
    - autori: ListView<Autore>
    - nomeAutore: TextField
    - cognomeAutore: TextField
    - anno: TextField
    - btnIndietro: Button
    - btnConferma: Button
    - btnAggiungiAutore: Button

    + init(): void
    + aggiungiAutore(): void
    + tornaIndietro(): void
    + conferma(): void
}


@enduml