@startuml ControllerSchermataLibro
class ControllerSchermataLibro {
    - btnLista: Button
    - btnAggiungi: Button
    - btnIndietro: Button
    - btnTitolo: Button
    - btnISBN: Button
    - btnPrimoAutore: Button

    + init(): void
    + schermataVisualizzaLibro(): void
    + schermataAggiungiLibro(): void
    + tornaIndietro(): void
    + ordinamentoPerTitolo(): void
    + ordinamentoPerISBN(): void
    + ordinamentoPerAutore(): void
}
@enduml