@startuml ControllerSchermataVisualizzautente

class ControllerSchermataVisualizzaUtente {
    - tabellaUtente: TableView<Utente>
    - colonnaNome: TableColumn<Utente,String>
    - colonnaCognome: TableColumn<Utente,String>
    - colonnaMatricola: TableColumn<Utente,Integer>
    - colonnaEmail: TableColumn<Utente,String>
    - colonnaElimina: TableColumn<Utente,Void>
    - colonnaModifica: TableColumn<Utente,Void>
    - btnIndietro: Button
    - btnRicerca: Button

    + init(): void
    + aggiungiBtnModifica(): void
    + aggiungiBtnElimina(): void
    + tornaIndietro(): void
    + cerca(): void
}


@enduml