@startuml ClassDiagram
skinparam linetype ortho
left to right direction

class Autore {
    - nome: String
    - cognome: String
    {static} + COGNOME: Comparator<Autore>

    + Autore(nome: String, cognome: String)
    {static}+getCOGNOME():Comparator<Autore>
    + getNome(): String
    + setNome(nome: String): String
    + getCognome(): String
    + setCognome(cognome: String): String
    + equals(o: Object): boolean
}

class Libro {
    - titolo: String
    - autori: List<Autore>
    - ISBN: String
    - anno: int
    - disponibile: boolean
    - copie: int
    {static} + final TITOLO: Comparator<Libro> 
    {static} + final ISBN: Comparator<Libro>
    {static} + final PRIMO_AUTORE: Comparator<Libro>

    + Libro(titolo: String, autori: List<Autore>, ISBN: String, anno: int, copie: int)
    + getTitolo(): String
    + setTitolo(titolo: String): void
    + getAutori(): List<Autore>
    + setAutori(autori: List<Autore>): void
    + modificaAutore(autore: Autore): void
    + getISBN(): String
    + setISBN(ISBN: String): void
    + getAnno(): int
    + setAnno(anno: int): void
    + getCopie(): int
    + setCopie(copie: int): void
    + aggiungiAutore(a: Autore): void
    + rimuoviAutore(a: Autore): void
    + getDisponibile(): boolean
    + setDisponibile(disponibile: boolean): void
    + equals(o: Object): boolean
    + ordinaAutori(): void
}

class Lista_Libri {
    - libri: List<Libro>

    + modificaCopie(String ISBN, int n): void
    + aggiungiLibro(libro: Libro): void
    + rimuoviLibro(libro: Libro): void
    + modificaLibro(libro: Libro): void
    + cercaPerTitolo(str: String): List<Libro>
    + cercaPerISBN(str: String): List<Libro>
    + cercaPerAutore(str: String): List<Autore>
    + ordina(cmp: Comparator<Libro>): void
    + checkISBN(ISBN: String): boolean
    + salvataggioLibri(nomefile: String): void
    + letturaLibri(nomefile: String): Lista_Libri
}

class Lista_Prestiti {
    - prestiti: List<Prestito>

    + getPrestiti(): List<Prestito>
    + setPrestiti(prestiti: List<Prestito>): void
    + aggiungiPrestito(p: Prestito): boolean
    + rimuoviPrestito(p: Prestito): boolean
    + aggiornaRitardi(): List<Prestito>
    + cercaPerISBN(ISBN: String): List<Prestito>
    + cercaPerID(ID: int): List<Prestito>
    + cercaPerMatricola(Matricola: String): List<Prestito>
    + cercaPerData(dataScadenza: LocalDate): List<Prestito>
    + OrdinaLibriPerScadenza(cmp: Comparator<Prestito>): void
    + ModificaPrestito(old: Prestito,newer: Prestito):boolean
    + checkUtente(p: Prestito):boolean
    + salvataggioPrestiti(nomefile: String): void
    + letturaPrestiti(nomefile: String): void
}

class Lista_Utenti {
    - utenti: List<Utente>

    + aggiungiUtente(utente: Utente): void
    + rimuoviUtente(utente: Utente): void
    + modificaUtente(utente: Utente): Utente
    + getUtenti(): List<Utente>
    + setUtenti(utenti: List<Utente>): void
    + cercaPerMatricola(str: String): List<Utente>
    + cercaPerNomeCognome(str: String): List<Utente>
    + checkUtente(utente: Utente): boolean
    + salvataggioUtenti(nomefile: String): void
    + letturaUtenti(nomefile: String): Lista_Utenti
}

class Prestito {
    - ISBN: String
    - matricola: int
    - dataScadenza: LocalDate
    - ID: int
    {static} -counter:int
    {static} + SCADENZA: Comparator<Prestito> <<final>>
    + getComp():Comparator<Prestito>
    + getISBN(): String
    + setISBN(String: ISBN): void
    + getMatricola(): String
    + setMatricola(String: Matricola): void
    + getID(): int
    + getDataScadenza(): LocalDate
    + setDataScadenza(data: LocalDate): void
    + equals(o: Object): boolean
}

class Utente {
    - nome: String
    - cognome: String
    - matricola: int
    - mail: String

    + Utente(nome: String, cognome: String, matricola: int, mail: String)
    + getNome(): String
    + setNome(nome: String): void
    + getCognome(): String
    + setCognome(cognome: String): void
    + getMatricola(): int
    + setMatricola(matricola: int): void
    + getMail(): String
    + setMail(mail: String): void
    + equals(o: Object): boolean
}

class ControllerAggiungiLibro {
}

class ControllerModificaLibro {
}

class ControllerGestioneLibri {
}

class ControllerListaLibri {
}

class ControllerAggiungiPrestito {
}

class ControllerModificaPrestito {
}

class ControllerGestionePrestiti {
}

class ControllerListaPrestiti {
}

class ControllerListaRitardi {
}

class ControllerAggiungiUtente {
}

class ControllerModificaUtente {
}

class ControllerGestioneUtenti {
}

class ControllerListaUtenti {
}

class ControllerHome {
}

'sezione relazioni controller
ControllerAggiungiLibro ..> Libro
ControllerAggiungiLibro ..> Autore
ControllerAggiungiLibro ..> Lista_Libri

ControllerModificaLibro ..> Libro
ControllerModificaLibro ..> Autore
ControllerModificaLibro ..> Lista_Libri

ControllerGestioneLibri ..> Libro
ControllerGestioneLibri ..> Lista_Libri

ControllerListaLibri ..> Libro
ControllerListaLibri ..> Lista_Libri

ControllerAggiungiPrestito ..> Prestito
ControllerAggiungiPrestito ..> Libro
ControllerAggiungiPrestito ..> Lista_Prestiti
ControllerAggiungiPrestito ..> Lista_Libri
ControllerAggiungiPrestito ..> Lista_Utenti

ControllerModificaPrestito ..> Prestito
ControllerModificaPrestito ..> Libro
ControllerModificaPrestito ..> Lista_Prestiti
ControllerModificaPrestito ..> Lista_Libri
ControllerModificaPrestito ..> Lista_Utenti

ControllerGestionePrestiti ..> Prestito
ControllerGestionePrestiti ..> Lista_Prestiti
ControllerGestionePrestiti ..> Lista_Libri
ControllerGestionePrestiti ..> Lista_Utenti

ControllerListaPrestiti ..> Prestito
ControllerListaPrestiti ..> Libro
ControllerListaPrestiti ..> Lista_Prestiti
ControllerListaPrestiti ..> Lista_Libri
ControllerListaPrestiti ..> Lista_Utenti

ControllerListaRitardi ..> Prestito
ControllerListaRitardi ..> Libro
ControllerListaRitardi ..> Lista_Prestiti
ControllerListaRitardi ..> Lista_Libri
ControllerListaRitardi ..> Lista_Utenti

ControllerAggiungiUtente ..> Utente
ControllerAggiungiUtente ..> Lista_Utenti

ControllerModificaUtente ..> Utente
ControllerModificaUtente ..> Lista_Utenti

ControllerGestioneUtenti ..> Utente
ControllerGestioneUtenti ..> Lista_Utenti

ControllerListaUtenti ..> Utente
ControllerListaUtenti ..> Lista_Utenti

ControllerHome ..> Lista_Libri
ControllerHome ..> Lista_Prestiti
ControllerHome ..> Lista_Utenti






'sezione relazioni

Libro "1.." o-- "1.." Autore
Lista_Libri "1" o-- "1..*" Libro
Lista_Utenti "1" o-- "1..*" Utente
Lista_Prestiti "1" o-- "1..*" Prestito
Libro "1" <-- "1" Prestito
Utente "1" o-- "1..3" Prestito

note as N1
Metodi e attributi dei controller 
sono implementati in file contenuti 
nella directory IndividualClassControllersCode e nel
file ControllersOnlyDiagramCodeExplicit ai fini 
di una migliore rappresentazione
end note