@startuml ClassDiagram
skinparam linetype ortho

class Autore {
    - nome: String
    - cognome: String
    {static} + COGNOME: Comparator<Autore>

    + Autore(nome: String, cognome: String)
    {static}+getCOGNOME():Comparator<Autore>
    + getNome(): String
    + setNome(nome: String): String
    + getCognome(): String
    + setCognome(cognome: String): String
    + equals(o: Object): boolean
}

class Libro {
    - titolo: String
    - autori: List<Autore>
    - ISBN: String
    - anno: int
    - disponibile: boolean
    - copie: int
    {static} + final TITOLO: Comparator<Libro> 
    {static} + final ISBN: Comparator<Libro>
    {static} + final PRIMO_AUTORE: Comparator<Libro>

    + Libro(titolo: String, autori: List<Autore>, ISBN: String, anno: int, copie: int)
    + getTitolo(): String
    + setTitolo(titolo: String): void
    + getAutori(): List<Autore>
    + setAutori(autori: List<Autore>): void
    + modificaAutore(autore: Autore): void
    + getISBN(): String
    + setISBN(ISBN: String): void
    + getAnno(): int
    + setAnno(anno: int): void
    + getCopie(): int
    + setCopie(copie: int): void
    + aggiungiAutore(a: Autore): void
    + rimuoviAutore(a: Autore): void
    + getDisponibile(): boolean
    + setDisponibile(disponibile: boolean): void
    + equals(o: Object): boolean
    + ordinaAutori(): void
}

class Lista_Libri {
    - libri: List<Libro>

    + modificaCopie(String ISBN, int n): void
    + aggiungiLibro(libro: Libro): void
    + rimuoviLibro(libro: Libro): void
    + modificaLibro(libro: Libro): void
    + cercaPerTitolo(str: String): List<Libro>
    + cercaPerISBN(str: String): List<Libro>
    + cercaPerAutore(str: String): List<Autore>
    + ordina(cmp: Comparator<Libro>): void
    + checkISBN(ISBN: String): boolean
    + salvataggioLibri(nomefile: String): void
    + letturaLibri(nomefile: String): Lista_Libri
}

class Lista_Prestiti {
    - prestiti: List<Prestito>

    + getPrestiti(): List<Prestito>
    + setPrestiti(prestiti: List<Prestito>): void
    + aggiungiPrestito(p: Prestito,libri: Lista_Libri,utenti: Lista_Utenti): String
    + rimuoviPrestito(p: Prestito): String
    + aggiornaRitardi(): List<Prestito>
    + cercaPerISBN(ISBN: String): List<Prestito>
    + cercaPerID(ID: int): List<Prestito>
    + cercaPerMatricola(Matricola: int): List<Prestito>
    + cercaPerData(dataScadenza: LocalDate): List<Prestito>
    + OrdinaLibriPerScadenza(cmp: Comparator<Prestito>): void
    + ModificaPrestito(p: Prestito,l: Prestito):String
    + checkUtente(p: Prestito):boolean
    + salvataggioPrestiti(nomefile: String): void
    + letturaPrestiti(nomefile: String): void
}

class Lista_Utenti {
    - utenti: List<Utente>

    + aggiungiUtente(utente: Utente): void
    + rimuoviUtente(utente: Utente): void
    + modificaUtente(utente: Utente): Utente
    + getUtenti(): List<Utente>
    + setUtenti(utenti: List<Utente>): void
    + cercaPerMatricola(str: String): List<Utente>
    + cercaPerNomeCognome(str: String): List<Utente>
    + checkUtente(utente: Utente): boolean
    + salvataggioUtenti(nomefile: String): void
    + letturaUtenti(nomefile: String): Lista_Utenti
}

class Prestito {
    - ISBN: String
    - matricola: int
    - dataScadenza: LocalDate
    - ID: int
    {static} -counter:int
    {static} + SCADENZA: Comparator<Prestito> <<final>>
    + getComp():Comparator<Prestito>
    + getISBN(): String
    + setISBN(String: ISBN): void
    + getMatricola(): int
    + setMatricola(int: Matricola): void
    + getID(): int
    + getDataScadenza(): LocalDate
    + setDataScadenza(data: LocalDate): void
    + equals(o: Object): boolean
}

class Utente {
    - nome: String
    - cognome: String
    - matricola: int
    - mail: String

    + Utente(nome: String, cognome: String, matricola: int, mail: String)
    + getNome(): String
    + setNome(nome: String): void
    + getCognome(): String
    + setCognome(cognome: String): void
    + getMatricola(): int
    + setMatricola(matricola: int): void
    + getMail(): String
    + setMail(mail: String): void
    + equals(o: Object): boolean
}

class ControllerSchermataAggiungiLibro {

}

class ControllerSchermataAggiungiPrestito {

}

class ControllerSchermataAggiungiUtente {

}

class ControllerSchermataModificaLibro {

}

class ControllerSchermataModificaPrestito {

}

class ControllerSchermataModificaRitardo {

}

class ControllerSchermataModificaUtente {

}

class ControllerSchermataVisualizzaLibro {

}

class ControllerSchermataVisualizzaPrestito {

}

class ControllerSchermataVisualizzaRitardo {

}

class ControllerSchermataVisualizzaUtente {

}

'sezione relazioni

Libro "1.." o-- "1.." Autore
Lista_Libri "1" o-- "1..*" Libro
Lista_Utenti "1" o-- "1..*" Utente
Lista_Prestiti "1" o-- "1..*" Prestito
Libro "1" <-- "1" Prestito
Utente "1" o-- "1..3" Prestito

'Dipendenze Controller Libro
'Schermata Libro
'Visualizzazione Libro
ControllerSchermataVisualizzaLibro ..>Lista_Libri
ControllerSchermataVisualizzaLibro ..> ControllerSchermataModificaLibro
ControllerSchermataModificaLibro ..> Autore
ControllerSchermataModificaLibro ..> Lista_Libri
'Aggiunta Libro
ControllerSchermataAggiungiLibro ..> Autore
ControllerSchermataAggiungiLibro ..> Lista_Libri


'Dipendenze Controller Utente
'Schermata Utente
'Visualizzazione Utente
ControllerSchermataVisualizzaUtente ..>Lista_Utenti
ControllerSchermataVisualizzaUtente ..> ControllerSchermataModificaUtente
ControllerSchermataModificaUtente..>Lista_Utenti
'Aggiunta Utente
ControllerSchermataAggiungiUtente ..>Lista_Utenti


'Dipendenze Controller Prestito
'Schermata prestito

ControllerSchermataVisualizzaPrestito ..> ControllerSchermataModificaPrestito 
ControllerSchermataVisualizzaPrestito ..> Lista_Prestiti
ControllerSchermataModificaPrestito ..> Utente
ControllerSchermataModificaPrestito..> Lista_Prestiti
'Aggiunta Prestito
ControllerSchermataAggiungiPrestito ..>Utente
ControllerSchermataAggiungiPrestito ..>Lista_Prestiti


'Dipendenze Controller Ritardo
'Schermata Ritardo
'Visualizzazione Ritardo
ControllerSchermataVisualizzaRitardo ..>Lista_Prestiti
ControllerSchermataVisualizzaRitardo ..>ControllerSchermataModificaRitardo
ControllerSchermataModificaRitardo ..>Utente
ControllerSchermataModificaRitardo ..>Lista_Prestiti

note as N1
Metodi e attributi dei controller 
sono implementati in file contenuti 
nella directory IndividualClassControllersCode e nel
file ControllersOnlyDiagramCodeExplicit ai fini 
di una migliore rappresentazione
end note
