@startuml GestioneUtenti
scale 1
left to right direction
actor bibliotecario as b
rectangle GestioneUtente{
usecase "Inserimento utente" as uc1
usecase "Modifica utente" as uc2
usecase "Cancellazione utente" as uc3
usecase "Ricerca utente" as uc4
usecase "Visualizzazione lista utenti" as uc5
usecase "Utente non presente" as uc6

b--uc1
b--uc2
b--uc3
b--uc4
b--uc5


uc6 ..> uc4:<<extend>>

}

@enduml 
