@startuml ListaUtenti

class Lista_Utenti {
    - utenti: List<Utente>

    + aggiungiUtente(utente: Utente): void
    + rimuoviUtente(utente: Utente): void
    + modificaUtente(utente: Utente): Utente
    + getUtenti(): List<Utente>
    + setUtenti(utenti: List<Utente>): void
    + cercaPerMatricola(str: String): List<Utente>
    + cercaPerNomeCognome(str: String): List<Utente>
    + checkUtente(utente: Utente): boolean
    + salvataggioUtenti(nomefile: String): void
    + letturaUtenti(nomefile: String): Lista_Utenti
}

@enduml
