@startuml ClasseUtente

class Utente {
    - nome: String
    - cognome: String
    - matricola: int
    - mail: String

    + Utente(nome: String, cognome: String, matricola: int, mail: String)
    + getNome(): String
    + setNome(nome: String): void
    + getCognome(): String
    + setCognome(cognome: String): void
    + getMatricola(): int
    + setMatricola(matricola: int): void
    + getMail(): String
    + setMail(mail: String): void
    + equals(o: Object): boolean
}

@enduml
