@startuml ClassePrestito

class Prestito {
    - ISBN: String
    - utente: Utente
    - dataScadenza: LocalDate
    {static} - ID: int
    {static} + SCADENZA: Comparator<Prestito> <<final>>

    + getLibro(): Libro
    + setLibro(libro: Libro): void
    + getUtente(): Utente
    + setUtente(utente: Utente): void
    + getID(): int
    + setID(ID: int): void
    + getDataScadenza(): LocalDate
    + setDataScadenza(data: LocalDate): void
    + equals(o: Object): boolean
}

@enduml
