@startuml
autonumber

participant "interfaccia" as g
participant "Lista Prestiti" as archiviop
participant "Prestito" as p
participant "Lista Utenti" as archiviou
participant "Lista Libri" as archiviol
participant "Archivio esterno Prestiti" as archivioe
activate g
activate archiviol
g->archiviol:checkISBN()
alt condizione ISBN non presente
    archiviol-->g:return false
else condizione ISBN presente
    archiviol-->g:return true
    deactivate archiviol
    g->archiviou:checkMatricola()
    activate archiviou
    alt condizione Matricola non presente
        archiviou-->g:return false
    else condizione Matricola presente
        archiviou-->g:return true
        deactivate archiviou
        g->archiviop:checkUtente()
        activate archiviop
        alt condizione Utente ha 3 prestiti attivi
            archiviop-->g:return true
        else condizione Utente non ha 3 prestiti attivi
            archiviop-->g:return false
            g->p:Prestito()
            activate p
            p-->g:return Prestito
            deactivate p
            g->archiviop:aggiungiPrestito()
           
            g->archiviop:salvataggioPrestiti()
            deactivate archiviop
        end
    end
end
deactivate g
@enduml
