@startuml
autonumber

participant "interfaccia" as g
participant "Lista Prestiti" as archiviop
participant "Prestito" as p
participant "Lista Utenti" as archiviou
participant "Lista Libri" as archiviol
participant "Archivio esterno Prestiti" as archivioe
activate g

g->archiviop:aggiungiPrestito()
activate archiviop
archiviop->archiviop:checkUtente()
alt condizione 3 prestiti associati all'Utente
    archiviop-->g:return "Ci sono già 3 prestiti associati a questo utente"
else condizione meno di 3 prestiti associati all'Utente
    archiviop->archiviou:checkMatricola()
    activate archiviou
    alt Matricola presente
        archiviop->archiviol:checkISBN()
        activate archiviol
        alt condizione ISBN presente
            archiviop->archiviol:checkCopie()
            alt condizione copie disponibili
                archiviop->archiviop:add()   
                archiviop->archiviop:OrdinaPerScadenza() 
                archiviop->archiviol:modificaCopie()
                archiviop-->g:return "Prestito inserito"
                g->archiviop:salvataggioPrestiti()
                archiviop-->archivioe: Lista salvata
            else condizione copie non disponibili
                archiviop-->g:return "Non ci sono copie disponibili"
            end
        else condizione ISBN non presente
            archiviop-->g:return "ISBN non presente nella Lista Libri"
        end
    else condizione Matricola non presente
        archiviop-->g:return "Utente non presente"
    end
end

@enduml