@startuml RegistrazioneRestituzione
title Registrazione di una restituzione

participant "interfaccia" as UI
participant "Lista Prestiti" as ListaPrestiti
participant "Lista Libri" as ListaLibri
participant "Archivio esterno Prestiti" as ArchPrestiti

note over UI
Registrazione della restituzione di un prestito.
Il sistema ricerca il prestito, aggiorna le copie
del libro associato e rimuove il prestito dagli archivi.
end note

UI -> ListaPrestiti: rimuoviPrestito()
activate ListaPrestiti

ListaPrestiti -> ListaPrestiti: contains()
alt Prestito trovato (return contains true)
    ListaPrestiti -> ListaPrestiti: remove()
    ListaPrestiti-->UI:return true
    UI->ListaLibri:ModificaCopie()
    UI -> ListaPrestiti: salvataggioPrestiti()
else Prestito non trovato
    ListaPrestiti --> UI: return false
end

deactivate ListaPrestiti

@enduml