@startuml ControllerSchermataPrestiti

class ControllerSchermataPrestiti {
    - btnLista: Button
    - btnAggiungi: Button
    - btnIndietro: Button

    + init(): void
    + schermataVisualizzaPrestito(): void
    + schermataAggiungiPrestito(): void
    + tornaIndietro(): void
}

@enduml