@startuml ControllerSchermataPrestito


class ControllerSchermataPrestito {
    - btnLista: Button
    - btnAggiungi: Button
    - btnIndietro: Button

    + init(): void
    + schermataVisualizzaPrestito(): void
    + schermataAggiungiPrestito(): void
    + tornaIndietro(): void
}
@enduml