@startuml CancellazioneUtente
start 
:Accesso area gestione utenti;
:Visualizzazione lista utenti;
repeat 
:Ricerca utente;
repeat while (utente non trovato) is (sì (notifica))

:Selezione utente;

:Conferma Cancellazione;
:Rimozione Utente da archivio;
:Rimozione Utente da file esterno;
:Notifica rimozione con successo;

stop 
@enduml 