@startuml CancellazioneLibro 
start 
:Accesso area gestione libri;
:Ricerca libro;
:Accesso area rimozione libro;
:Rimozione di tutte le copie;
:Aggiornamento file esterno;
:Notifica rimozione con successo;
stop 
@enduml 