@startuml InserimentoLibro

start
:Accesso area gestione libri;
:Accesso area aggiungi libro;
repeat
    :Inserisci dati libro;
    :Verifica correttezza dati;
    if(Dati corretti) then (sì)
    break
    else(no (notifica))
    endif  
repeat while

if(Libro presente in archivio) then (sì)
:Aggiorna numero copie; 
else (no)
:Aggiungi libro in archivio;
endif

:Salva libro;
:Aggiornamento file esterno;
stop

@enduml