@startuml InserimentoUtente
start 
:Accesso are Gestione utenti;
:Selezione aggiungi utente;
repeat 
repeat
:Inserimento nome;
:Inserimento cognome;
:Inserimento matricola;
:Inserimento e-mail universitaria;
repeat while (Formato dati non corretto) is (sì)
repeat while (matricola già registrata) is (sì)

:Conferma dati inseriti;
:Conferma registrazione utente;
:Aggiornamento file esterno;
stop 
@enduml