@startuml ModificaUtente
start

:Accesso area gestione utenti;
:Accesso area modifica utente;
if(Operazione richiesta) then (Ricerca)
:Ricerca utente;
else (Visualizzazione);
:Visualizzazione lista utenti;
endif 

repeat 
:Selezione utente;
repeat while (Utente non trovato) is (sì)

:Visualizzazione dati utente;

repeat 
:Modifica dati;
repeat while (Dati errati) is (sì)

:Conferma modifica;
:Aggiornamento file esterno;

stop

@enduml