@startuml ModificaCopieLibro
start 

:Accesso area gestione libri;
:Ricerca libro;
:Accesso area copie libro;
repeat
:Scelta operazione da eseguire;
if(operazione selezionata) then (Aggiunta)
:Aggiunta copie;
else (Rimozione)
:Rimozione copie;
endif
repeat while (copie insufficienti) is (sì)
:Aggiornamento file esterno;

stop
@enduml