@startuml RicercaRitardo

start 

:Accesso area gestione prestiti;
:Accesso ricerca ritardo;


if(Ricerca per ISBN ) then
elseif(Ricerca per ID) then
elseif(Ricerca per matricola) then 
endif


:Visualizzazione elenco ritardi;

stop 

@enduml 