@startuml RicercaLIbro
start 
:Accesso area gestione libri;
:Ricerca libro;
repeat
:Inserimento dati;
repeat while (dati errati) is (sì)
if(Libro presente) then (sì)
:Visualizzazione libro/i ricercato/i;
else (no)
:Visualizzazione lista vuota;
endif
stop 
@enduml 