@startuml RicercaPrestito
start 
:Accesso area prestito;
:Accesso ricerca prestito;


if(Ricerca per ISBN ) then
elseif(Ricerca per ID) then
elseif(Ricerca per matricola) then 
endif
:Visualzzazione presiti associati;

stop 
@enduml 