@startuml RimozioneRitardo
start 
:Accesso area gestione prestiti;
:Accesso visualizza prestiti;
if(Lista vuota) then (no)
:Visualizzazione prestiti per data di restituzione;

repeat 
:Ricerca ritardo;
repeat while (ritardo trovato) is (no)

:Rimozione ritardo;
:Aggiornamento file esterno;

else (sì)

endif

stop 
@enduml