@startuml ControllerSchermataIniziale

class ControllerSchermataIniziale {
    - btnLibro: Button
    - btnUtente: Button
    - btnPrestito: Button
    - btnRitardo: Button

    + init(): void
    + schermataLibro(): void
    + schermataUtente(): void
    + schermataPrestito(): void
    + schermataRitardo(): void
}
@enduml